# Generated by Django 4.2.2 on 2023-06-11 02:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_title_product_name_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.CharField(max_length=10)),
                ('address', models.CharField(default='', max_length=200)),
                ('address_line_1', models.CharField(default='', max_length=100)),
                ('address_line_2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=10)),
                ('delivery_date', models.DateField(default=datetime.datetime.now)),
                ('delivery_time', models.TimeField(default=django.utils.timezone.now)),
                ('payment_status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
            ],
        ),
    ]
